version: '3.8'
name: test

services:
  eureka-server:
    container_name: test-eureka
    build:
      context: .
      dockerfile: Dockerfile
      target: eureka-server
    ports:
      - "8761:8761"

  mysql:
    image: mysql:8.0
    container_name: test-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ambulance_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    depends_on:
      - eureka-server

  api-gateway:
    container_name: test-gateway
    build:
      context: .
      dockerfile: Dockerfile
      target: api-gateway
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - mysql
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  route-optimization-service:
    container_name: test-route
    build:
      context: .
      dockerfile: Dockerfile
      target: route-service
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
      - api-gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  ambulance-service:
    container_name: test-ambulance
    build:
      context: .
      dockerfile: Dockerfile
      target: ambulance-service
    ports:
      - "8095:8095"
    depends_on:
      - eureka-server
      - mysql
      - api-gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ambulance_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  dispatch-coordination-service:
    container_name: test-dispatch
    build:
      context: .
      dockerfile: Dockerfile
      target: dispatch-service
    ports:
      - "8096:8096"
    depends_on:
      - eureka-server
      - mysql
      - api-gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ambulance_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  hospital-management-service:
    container_name: test-hospital
    build:
      context: .
      dockerfile: Dockerfile
      target: hospital-service
    ports:
      - "8093:8093"
    depends_on:
      - eureka-server
      - mysql
      - api-gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ambulance_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  mysql_data:
