version: '3.8'

services:
  eureka-server-test:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    ports:
      - "8771:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  ambulance-service-test:
    build:
      context: .
      dockerfile: Ambulance_Service/Dockerfile
    ports:
      - "8091:8081"
    depends_on:
      eureka-server-test:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server-test:8761/eureka/

  hospital-service-test:
    build:
      context: .
      dockerfile: hospital-management-service/Dockerfile
    ports:
      - "8093:8083"
    depends_on:
      eureka-server-test:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server-test:8761/eureka/

  route-optimization-test:
    build:
      context: .
      dockerfile: route-optimization-service/Dockerfile
    ports:
      - "8094:8084"
    depends_on:
      eureka-server-test:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server-test:8761/eureka/

networks:
  default:
    name: ambulance-network-test
